### ISSUE TITLE
could you release the latest version 

### ISSUE THREAD

**Issue by nemccarthy** [mkotsur/aws-lambda-scala#1]
promising lib, looks like the mvn central release is out of date

**Comment by mkotsur** [comment]
@nemccarthy the new version has just been released. Sorry for the delay, something is wrong with github notifications settings: I haven't got an email.

It's now on [Sonatype Releases repo](https://oss.sonatype.org/#nexus-search;quick~aws-lambda-scala), should be in Maven Central in no time ;-)

**Comment by mkotsur** [comment]
@nemccarthy by the way, I'd be interested to hear any feedback about existing/missing features.
