### ISSUE TITLE
Comparison to serverless + aws-scala-sbt

### ISSUE THREAD

**Issue by thunderkid** [mkotsur/aws-lambda-scala#13]
I'm just exploring scala lambdas, and I was starting to use the `serverless` project with the `aws-scala-sbt` plugin. It works for a single toy function, but I don't have a good picture of how cleanly I can keep my source structured as I add more functionality. (And their local invoke is currently broken which would add a fairly annoying overhead to testing...)
Then I came across your project, which looks like an interesting alternative. I saw your comment about new docs coming soon, and I wondered whether you could perhaps include a quick list of pros and cons in comparison to `serverless`. In terms of getting started, they provide `serverless create-template` which gets you up and running with a sample very easily. Looking at your project it's not clear to me how to get started since I'm not familiar with SAM. Will you be including a simple setup example, and do you consider this project ready for widespread use yet?
Thanks.

**Comment by mkotsur** [comment]
Hi there. Thanks for your interest. I would not consider myself an expert
in SAM, and therefore the scope of the library is really small: it just
helps you write somewhat cleaner lambda functions in Scala (compared to
just using the java lib from AWS) and takes care of (de)serialization of
input and output.

The library is totally agnostic of the way you organize the code, build and
deploy. So, sorry, this project will not help you with the complexity of
SAM and issues with testing, but it can help reducing boilerplate you’ll
need to write for each function. Does this make sense?

You are right, I should make it clear in the readme, thanks for posting the
issue.

**Comment by thunderkid** [comment]
Makes sense, thanks.
I was thinking that if you provided a complete starting example with two lambda functions, that would showcase how much boilerplate your project allows us to remove. (Two gives a better sense of how much DRY could be achieved.) If it's a good fit, users would have the option to learn more SAM themselves as needed, but they'd have a starting point to build from.

**Comment by mkotsur** [comment]
https://medium.com/@mkotsur/this-is-why-you-should-consider-using-aws-lambda-scala-6b3ea841f8b0

Would you say that this post answers your questions? I'll add link to it to the README.

Providing a good starting example would be nice, but it's a bit out of scope for this library. Serverless provides an example, and I'm just explaining how aws-lambda-scala can help you write more pure Scala.

**Comment by thunderkid** [comment]
Sorry about the delay. Yes thanks, that answers the question I was asking. I didn't understand that it could be run in addition to serverless - I thought required SAM instead. It looks very useful and I shall now try to implement it...

**Comment by mkotsur** [comment]
Great, thanks for the feedback.

**Comment by mkotsur** [comment]
Yes, version `0.0.11` is basically the same one as `0.0.13`, which is the latest one. There's been a bit of confusion: `0.0.12` has been accidentally released only for Scala `2.11`, but starting from `0.0.13` both versions of Scala will be supported.
