### ISSUE TITLE
Give lambda context

### ISSUE THREAD

**Issue by srenault** [mkotsur/aws-lambda-scala#4]
Why don't give the lambda `com.amazonaws.services.lambda.runtime.Context` here?

https://github.com/mkotsur/aws-lambda-scala/blob/66c65383a2592c801fbfefb03b868151cc31fe22/src/main/scala/io/github/mkotsur/aws/handler/Lambda.scala#L116

**Comment by mkotsur** [comment]
Hi Sébastien. I guess, I haven't done that because I didn't really need context in my lambdas and tried to keep the API as simple as possible. But if you need it to be there, I can definitely add it.

**Comment by srenault** [comment]
I think It could be interesting to have it. For instance, to get the logger.

**Comment by mkotsur** [comment]
I do realize it's not super quick, but still... the fix is released with 0.0.10! Should be in Maven Central soon. Would appreciate feedback you steel need it @srenault.

And Happy New Year! :christmas_tree: :santa: :bell:
